# Generated by Django 3.0 on 2019-12-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecomments', models.CharField(max_length=15)),
                ('ename', models.CharField(max_length=100)),
                ('eemail', models.CharField(max_length=100)),
                ('edate', models.DateField()),
                ('eblogid', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
    ]
