# Generated by Django 3.0 on 2019-12-23 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20191221_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='eblogid',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='edate',
        ),
    ]
