# Generated by Django 3.0 on 2019-12-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20191223_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='edate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='edate',
            field=models.DateField(auto_now=True),
        ),
    ]
