# Generated by Django 3.0 on 2019-12-24 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20191224_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='edate',
            new_name='date',
        ),
    ]
